const data = {
  products: [
    {
      name: "Set Of Leather Trays",
      slug: " nike-slim-shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 3450,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality leather products",
    },
    {
      name: "Cutlery Box And Cutlery Stand",
      slug: " nike-slim-shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 3450,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality leather products",
    },
    {
      name: "Dark Brown Cutlery Box",
      slug: " nike-slim-shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 3450,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality leather products",
    },
    {
      name: "Dark Brown Cutlery box",
      slug: " nike-slim-shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 3450,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality leather products",
    },
  ],
};
export default data;
